project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"       # Render all .qmd files...
    - "!slides/Rmarkdown/assets-day4/"
    - "!slides/Introduction/assets-day4/"

website:
  title: "BasicRCourseEMC_Slides"
  navbar:
    right:
      - icon: github
        href: https://github.com/dnieuw/BasicRCourseEMC_slides
        
format:
  html:
    theme: cosmo
    css: styles.css



